import React from "react";
import { Check, FileCheck2, FileDown, Pencil, Plus, Save, Trash2, X } from "lucide-react";
import type { Match, Role } from "../../types/wpolo";
import { generateMatchProtocolPdf } from "../../lib/matchProtocolPdf";
import { PROTOCOL_EVENT_OPTIONS, eventLabel, eventSymbol, loadProtocol, loadProtocolContext, normalizeProtocolClock, playerGoals, playerMajorFoulEvents, playerMajorFouls, protocolScore, requiresDisciplinaryDecision, saveProtocol, type MatchProtocolDraft, type ProtocolContext, type ProtocolEvent, type ProtocolEventKind, type ProtocolPlayer, type ProtocolTeam } from "../../lib/matchProtocol";

type User = { name: string; role: Role; club?: string };
const input = "w-full rounded-lg border border-slate-200 bg-white px-2.5 py-2 text-sm outline-none focus:border-sky-400";
const isAdminUser = (user: User) => String(user.role).split(/[-+,\s]+/).includes("Admin");
const isDelegate = (user: User, match: Match, delegateName?: string) => isAdminUser(user) || (delegateName || match.delegate) === user.name;
const periodLabel = (p: 1|2|3|4|"PS") => p === "PS" ? "Rzuty karne" : `${["I","II","III","IV"][p - 1]} kwarta`;
const clockSeconds = (clock: string) => { const [minutes, seconds] = clock.split(":").map(Number); return (minutes || 0) * 60 + (seconds || 0); };

export function MatchProtocolWorkspace({ match, user, onClose }: { match: Match; user: User; onClose: () => void }) {
  const [protocol, setProtocol] = React.useState<MatchProtocolDraft>(() => loadProtocol(match.id));
  const [context, setContext] = React.useState<ProtocolContext | null>(null);
  const [loading, setLoading] = React.useState(true);
  const [editorOpen, setEditorOpen] = React.useState(false);
  const [editingId, setEditingId] = React.useState<string | null>(null);
  const [team, setTeam] = React.useState<ProtocolTeam>("home");
  const [kind, setKind] = React.useState<ProtocolEventKind>("goal");
  const [playerId, setPlayerId] = React.useState("");
  const [clock, setClock] = React.useState("");
  const [highlightPlayer, setHighlightPlayer] = React.useState<string | null>(null);
  const [highlightFoulPlayer, setHighlightFoulPlayer] = React.useState<string | null>(null);
  const [thirdFoulPlayer, setThirdFoulPlayer] = React.useState<ProtocolPlayer | null>(null);
  const [eventMenu, setEventMenu] = React.useState<"foul" | "other" | null>(null);
  const [shootoutTeam, setShootoutTeam] = React.useState<ProtocolTeam>("home");
  const [shootoutPlayerId, setShootoutPlayerId] = React.useState("");

  React.useEffect(() => { let active = true; setLoading(true); loadProtocolContext(match).then(v => { if (!active) return; setContext(v); setProtocol(p => ({ ...p, homePlayers: p.homePlayers.length ? p.homePlayers : v.homePlayers, awayPlayers: p.awayPlayers.length ? p.awayPlayers : v.awayPlayers, referee1: p.referee1 || match.referees[0] || "", referee2: p.referee2 || match.referees[1] || "", delegateName: p.delegateName || match.delegate || "" })); }).finally(() => active && setLoading(false)); return () => { active = false; }; }, [match]);
  React.useEffect(() => { saveProtocol(protocol); }, [protocol]);
  const homePlayers = protocol.homePlayers.length ? protocol.homePlayers : context?.homePlayers || [], awayPlayers = protocol.awayPlayers.length ? protocol.awayPlayers : context?.awayPlayers || [];
  const players = team === "home" ? homePlayers : awayPlayers;
  const canApprove = isDelegate(user, match);
  const canSubmit = isAdminUser(user) || user.club === match.home || canApprove;
  const setup = protocol.status === "setup";
  const live = protocol.status === "live";
  const score = protocolScore(protocol.events);
  const timeouts = (side: ProtocolTeam) => protocol.events.filter(e => e.team === side && e.kind === "timeout").length;
  const selectedOption = PROTOCOL_EVENT_OPTIONS.find(o => o.value === kind)!;
  const selectedShootoutEvents = protocol.events.filter(event => event.period === "PS" && event.team === shootoutTeam && ["shootout_goal", "shootout_miss"].includes(event.kind));
  const selectedShootoutPlayers = shootoutTeam === "home" ? homePlayers : awayPlayers;
  const automaticShootoutPlayerId = selectedShootoutEvents.length >= 5 ? selectedShootoutEvents[selectedShootoutEvents.length % 5]?.playerId || "" : "";

  const openNew = (side: ProtocolTeam) => { setEditingId(null); setTeam(side); setKind("goal"); setPlayerId(""); setClock(""); setEditorOpen(true); };
  const openEdit = (event: ProtocolEvent) => { if (event.period === "PS") return alert("Próbę w serii rzutów karnych można poprawić przez usunięcie i ponowne dodanie."); setEditingId(event.id); setTeam(event.team); setKind(event.kind); setPlayerId(event.playerId || ""); setClock(event.clock); setEditorOpen(true); };
  const selectKind = (value: ProtocolEventKind) => { setKind(value); setEventMenu(null); if (["timeout", "official_penalty"].includes(value)) setPlayerId(""); };
  const saveEvent = () => {
    const formatted = normalizeProtocolClock(clock);
    if (!formatted) return alert("Wpisz czas zdarzenia.");
    if (clockSeconds(formatted) > 480) return alert("Czas kwarty nie może być większy niż 08:00.");
    if (!["timeout", "official_penalty"].includes(kind) && !playerId) return alert("Wybierz zawodnika.");
    if (kind === "timeout" && !editingId && timeouts(team) >= 2) return alert("Ta drużyna wykorzystała już dwa time-outy.");
    const previous = editingId ? protocol.events.find(e => e.id === editingId) : undefined;
    const editedIndex = editingId ? protocol.events.findIndex(e => e.id === editingId) : protocol.events.length;
    const samePeriodBefore = protocol.events.slice(0, editedIndex).filter(e => e.period === (previous?.period || protocol.currentPeriod));
    const samePeriodAfter = editingId ? protocol.events.slice(editedIndex + 1).filter(e => e.period === previous?.period) : [];
    const prior = samePeriodBefore[samePeriodBefore.length - 1];
    const next = samePeriodAfter[0];
    if (prior && clockSeconds(formatted) > clockSeconds(prior.clock)) return alert(`Czas musi być równy lub mniejszy od poprzedniego zdarzenia (${prior.clock}).`);
    if (next && clockSeconds(formatted) < clockSeconds(next.clock)) return alert(`Czas nie może być mniejszy od następnego zdarzenia (${next.clock}).`);
    const event: ProtocolEvent = { id: editingId || crypto.randomUUID(), period: previous?.period || protocol.currentPeriod, clock: formatted, team, playerId: playerId || null, kind, reason: previous?.reason, grossUnsporting: previous?.grossUnsporting, createdAt: previous?.createdAt || new Date().toISOString() };
    const withoutEdited = protocol.events.filter(e => e.id !== editingId);
    const becomesThirdMajor = playerId && ["exclusion","penalty","exclusion_substitution","brutality","double_exclusion"].includes(kind) && playerMajorFouls(withoutEdited, playerId) === 2;
    setProtocol(p => ({ ...p, events: editingId ? p.events.map(e => e.id === editingId ? event : e) : [...p.events, event] }));
    setEditorOpen(false); setEditingId(null);
    if (becomesThirdMajor) setThirdFoulPlayer(players.find(p => p.id === playerId) || null);
  };
  const startMatch = () => setProtocol(p => ({ ...p, status: "live" }));
  const endQuarter = () => {
    if (protocol.currentPeriod === "PS") return;
    if (protocol.currentPeriod === 4) { const regulation = protocolScore(protocol.events.filter(event => event.period !== "PS")); if (regulation.home !== regulation.away) return alert("Serię rzutów karnych można rozpocząć wyłącznie przy remisie po IV kwarcie."); if (confirm("Zakończyć IV kwartę i przejść do rzutów karnych?")) setProtocol(p => ({ ...p, currentPeriod: "PS" })); return; }
    setProtocol(p => ({ ...p, currentPeriod: (Number(p.currentPeriod) + 1) as 2|3|4 }));
  };
  const undoQuarter = () => {
    if (protocol.currentPeriod === 1) return;
    if (protocol.events.some(event => event.period === protocol.currentPeriod)) return alert("Najpierw usuń wydarzenia zapisane w bieżącej kwarcie.");
    setProtocol(p => ({ ...p, currentPeriod: p.currentPeriod === "PS" ? 4 : (Number(p.currentPeriod) - 1) as 1|2|3 }));
  };
  const setDecision = (id: string, field: "reason"|"grossUnsporting", value: string|boolean) => setProtocol(p => ({ ...p, events: p.events.map(e => e.id === id ? { ...e, [field]: value } : e) }));
  const submitProtocol = () => {
    if (!canSubmit) return alert("Protokół może zamknąć gospodarz, delegat lub administrator.");
    if (!protocol.finishedAt) return alert("Wpisz godzinę zakończenia spotkania.");
    if (protocol.events.some(e => requiresDisciplinaryDecision(e.kind) && (!e.reason?.trim() || typeof e.grossUnsporting !== "boolean"))) return alert("Uzupełnij uwagi i decyzję o rażącym niesportowym zachowaniu przy wszystkich oznaczonych zdarzeniach.");
    const submitted = { ...protocol, status: "submitted" as const, closedAt: new Date().toISOString(), closedBy: user.name }; setProtocol(submitted); saveProtocol(submitted);
  };
  const approveProtocol = () => { if (!canApprove) return; const approved = { ...protocol, status: "approved" as const, approvedAt: new Date().toISOString(), approvedBy: user.name }; setProtocol(approved); saveProtocol(approved); };
  const reopenProtocol = () => { if (!canApprove) return; setProtocol(p => ({ ...p, status: "setup", approvedAt: undefined, approvedBy: undefined })); };

  const shootoutEvents = (side: ProtocolTeam) => protocol.events.filter(event => event.period === "PS" && event.team === side && ["shootout_goal", "shootout_miss"].includes(event.kind));
  const shootoutComplete = (() => { const home = shootoutEvents("home"), away = shootoutEvents("away"); if (home.length < 5 || away.length < 5 || home.length !== away.length) return false; return home.filter(e => e.kind === "shootout_goal").length !== away.filter(e => e.kind === "shootout_goal").length; })();
  const addShootout = (scored: boolean) => {
    if (shootoutComplete) return alert("Seria rzutów karnych jest już rozstrzygnięta.");
    const sideEvents = shootoutEvents(shootoutTeam);
    const homeCount = shootoutEvents("home").length, awayCount = shootoutEvents("away").length;
    if (shootoutTeam === "home" && homeCount > awayCount) return alert("Teraz rzut karny wykonuje drużyna ciemnych.");
    if (shootoutTeam === "away" && awayCount >= homeCount) return alert("Teraz rzut karny wykonuje drużyna jasnych.");
    const automaticId = sideEvents.length >= 5 ? sideEvents[sideEvents.length % 5]?.playerId || "" : "";
    const selectedId = automaticId || shootoutPlayerId;
    if (!selectedId) return alert("Wybierz strzelca rzutu karnego.");
    const event: ProtocolEvent = { id: crypto.randomUUID(), period: "PS", clock: `K${sideEvents.length + 1}`, team: shootoutTeam, playerId: selectedId, kind: scored ? "shootout_goal" : "shootout_miss", createdAt: new Date().toISOString() };
    setProtocol(p => ({ ...p, events: [...p.events, event] })); setShootoutPlayerId(""); setShootoutTeam(shootoutTeam === "home" ? "away" : "home");
  };

  const updatePlayer = (side: ProtocolTeam, slot: number, field: "name" | "capNumber", value: string) => setProtocol(p => {
    const key = side === "home" ? "homePlayers" : "awayPlayers";
    const existing = p[key].find(player => player.slot === slot);
    const player: ProtocolPlayer = existing || { id: `manual-${side}-${slot}`, slot, capNumber: slot, name: "", isGoalkeeper: false, isCaptain: false };
    const updated = { ...player, [field]: field === "capNumber" ? Math.max(1, Number(value) || slot) : value };
    return { ...p, [key]: [...p[key].filter(item => item.slot !== slot), updated].sort((a, b) => a.slot - b.slot) };
  });

  const timeoutBoxes = (side: ProtocolTeam) => <div className="flex items-center gap-2 text-sm"><b>Time-out:</b>{[0,1].map(i => <span key={i} className={`grid h-7 w-7 place-items-center rounded border-2 font-black ${timeouts(side) > i ? "border-red-400 bg-red-50 text-red-600" : "border-slate-300 text-transparent"}`}>×</span>)}</div>;
  const teamCard = (side: ProtocolTeam, title: string, roster: typeof homePlayers) => <section className={`rounded-xl border ${side === "away" ? "border-sky-200 bg-sky-50" : "border-slate-200 bg-white"}`}>
    <div className="border-b p-3"><b>{title}</b><div className="mt-2 grid gap-2 sm:grid-cols-3"><input disabled={!setup} className={input} placeholder="Trener" value={side === "home" ? protocol.homeCoach : protocol.awayCoach} onChange={e => setProtocol(p => ({ ...p, [side === "home" ? "homeCoach" : "awayCoach"]: e.target.value }))}/><input disabled={!setup} className={input} placeholder="Oficjel 1" value={side === "home" ? protocol.homeOfficial1 : protocol.awayOfficial1} onChange={e => setProtocol(p => ({ ...p, [side === "home" ? "homeOfficial1" : "awayOfficial1"]: e.target.value }))}/><input disabled={!setup} className={input} placeholder="Oficjel 2" value={side === "home" ? protocol.homeOfficial2 : protocol.awayOfficial2} onChange={e => setProtocol(p => ({ ...p, [side === "home" ? "homeOfficial2" : "awayOfficial2"]: e.target.value }))}/></div></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[430px] text-xs"><thead><tr><th className="p-2 text-left">Czepek</th><th className="p-2 text-left">Zawodnik</th><th className="p-2">Bramki</th><th className="p-2" colSpan={3}>Przewinienia główne</th></tr></thead><tbody>{Array.from({length:15},(_,i)=>{const player=roster.find(p=>p.slot===i+1), goals=player?playerGoals(protocol.events,player.id):0, foulEvents=player?playerMajorFoulEvents(protocol.events,player.id):[];return <tr key={i} className={`border-t ${foulEvents.length>=3?"bg-red-50":""}`}><td className="w-20 p-2 font-bold">{setup?<input type="number" min={1} className="w-16 rounded border px-2 py-1" value={player?.capNumber||i+1} onChange={e=>updatePlayer(side,i+1,"capNumber",e.target.value)}/>:player?.capNumber||i+1}</td><td className="p-2">{setup?<input className="w-full rounded border px-2 py-1" placeholder="Imię i nazwisko" value={player?.name||""} onChange={e=>updatePlayer(side,i+1,"name",e.target.value)}/>:<>{player?.name||"—"}{player?.isCaptain?" (C)":""}{player?.isGoalkeeper?" (GK)":""}{foulEvents.length>=3?<span className="ml-2 font-bold text-red-600">WYKLUCZONY</span>:""}</>}</td><td className="p-2 text-center"><button disabled={!goals} onMouseEnter={()=>player&&setHighlightPlayer(player.id)} onMouseLeave={()=>setHighlightPlayer(null)} className={goals?"rounded bg-amber-100 px-2 py-1 font-bold text-amber-800":""}>{goals||"—"}</button></td>{[0,1,2].map(n=>{const foul=foulEvents[n],danger=foul&&(n===2||["exclusion_substitution","brutality"].includes(foul.kind));return <td key={n} className="w-10 p-2 text-center">{foul?<button onMouseEnter={()=>player&&setHighlightFoulPlayer(player.id)} onMouseLeave={()=>setHighlightFoulPlayer(null)} className={`rounded px-1.5 py-1 font-black ${danger?"bg-red-600 text-white":"bg-slate-200 text-slate-800"}`}>{eventSymbol(foul.kind)||"W"}</button>:""}</td>})}</tr>})}</tbody></table></div>
    <div className="flex flex-wrap items-center justify-between gap-3 border-t p-3">{timeoutBoxes(side)}{live && protocol.currentPeriod!=="PS" ? <button onClick={()=>openNew(side)} className={`inline-flex items-center gap-2 rounded-lg border-2 px-4 py-2 font-semibold shadow-sm ${side==="home"?"border-slate-400 bg-white text-[#061a33]":"border-[#061a33] bg-[#061a33] text-white"}`}><Plus className="h-4 w-4"/>Dodaj wydarzenie</button>:null}</div>
  </section>;

  return <div className="fixed inset-0 z-[120] overflow-y-auto bg-slate-950/60 p-2 sm:p-5"><div className="mx-auto min-h-full max-w-7xl rounded-2xl bg-slate-50 shadow-2xl">
    <header className="sticky top-0 z-10 flex justify-between gap-3 rounded-t-2xl border-b bg-white p-4"><div><div className="text-xs font-bold uppercase tracking-widest text-amber-600">Prywatny prototyp — tylko localhost</div><h2 className="text-xl font-bold">Protokół: {match.home} — {match.away}</h2><p className="text-sm text-slate-600">{match.date} • {match.location} • Sędziowie: {[protocol.referee1,protocol.referee2].filter(Boolean).join(", ")||"—"} • Delegat: {protocol.delegateName||"—"}</p></div><button onClick={onClose} className="rounded-lg border p-2"><X/></button></header>
    <main className="space-y-4 p-3 sm:p-5">{loading?<div className="rounded-xl bg-white p-4">Pobieranie składów…</div>:null}
      <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-white p-3"><div><small className="uppercase text-slate-500">Status protokołu</small><div className="text-xl font-bold">{setup?"Przygotowanie":live?periodLabel(protocol.currentPeriod):protocol.status==="submitted"?"Oczekuje na zatwierdzenie":"Zatwierdzony"}</div></div><div className="rounded-xl bg-[#061a33] px-4 py-2 text-xl font-bold text-white">{score.home} : {score.away}</div></div>
      <section className="rounded-xl border bg-white p-3"><h3 className="font-bold">Obsada stolika i meczu</h3><div className="mt-3 grid gap-2 md:grid-cols-3"><input disabled={!setup} className={input} placeholder="Arbiter I" value={protocol.referee1} onChange={e=>setProtocol(p=>({...p,referee1:e.target.value}))}/><input disabled={!setup} className={input} placeholder="Arbiter II" value={protocol.referee2} onChange={e=>setProtocol(p=>({...p,referee2:e.target.value}))}/><input disabled={!setup} className={input} placeholder="Delegat" value={protocol.delegateName} onChange={e=>setProtocol(p=>({...p,delegateName:e.target.value}))}/><input disabled={!setup} className={input} placeholder="Protokolant (opcjonalnie)" value={protocol.protocolSecretary} onChange={e=>setProtocol(p=>({...p,protocolSecretary:e.target.value}))}/><input disabled={!setup} className={input} placeholder="Sędzia czasu I (opcjonalnie)" value={protocol.timeSecretary1} onChange={e=>setProtocol(p=>({...p,timeSecretary1:e.target.value}))}/><input disabled={!setup} className={input} placeholder="Sędzia czasu II (opcjonalnie)" value={protocol.timeSecretary2} onChange={e=>setProtocol(p=>({...p,timeSecretary2:e.target.value}))}/><input disabled={!setup} className={input} placeholder="Sędzia bramkowy I (opcjonalnie)" value={protocol.goalSecretary1} onChange={e=>setProtocol(p=>({...p,goalSecretary1:e.target.value}))}/><input disabled={!setup} className={input} placeholder="Sędzia bramkowy II (opcjonalnie)" value={protocol.goalSecretary2} onChange={e=>setProtocol(p=>({...p,goalSecretary2:e.target.value}))}/></div></section>
      <div className="grid gap-3 lg:grid-cols-2">{teamCard("home",match.home,homePlayers)}{teamCard("away",match.away,awayPlayers)}</div>
      <div className="flex flex-wrap justify-center gap-3 rounded-xl border bg-white p-3">{setup?<button onClick={startMatch} className="rounded-xl bg-green-600 px-8 py-3 text-lg font-black text-white">{protocol.events.length?"Wznów edycję protokołu":"Rozpocznij mecz"}</button>:live?<><button onClick={undoQuarter} disabled={protocol.currentPeriod===1} className="rounded-xl border px-6 py-3 font-bold disabled:opacity-40">Cofnij koniec kwarty</button>{protocol.currentPeriod!=="PS"?<button onClick={endQuarter} className="rounded-xl border border-amber-300 bg-amber-50 px-8 py-3 text-lg font-bold text-amber-800">Koniec kwarty</button>:null}</>:null}</div>
      {live&&protocol.currentPeriod==="PS"?<section className="rounded-2xl border-2 border-amber-300 bg-amber-50 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-xl font-black">Seria rzutów karnych</h3><p className="text-sm text-slate-600">Pierwszych pięciu strzelców wybierasz ręcznie. Kolejne serie powtarzają tę samą kolejność.</p></div><div className="rounded-lg bg-white px-4 py-2 font-black">Karne: {shootoutEvents("home").filter(e=>e.kind==="shootout_goal").length} : {shootoutEvents("away").filter(e=>e.kind==="shootout_goal").length}</div></div><div className="mt-4 grid gap-3 md:grid-cols-[auto_1fr_auto_auto]"><div className="flex gap-2"><button onClick={()=>{setShootoutTeam("home");setShootoutPlayerId("")}} className={`rounded-lg px-3 py-2 font-bold ${shootoutTeam==="home"?"bg-white ring-2 ring-slate-500":"bg-white/60"}`}>Jasne</button><button onClick={()=>{setShootoutTeam("away");setShootoutPlayerId("")}} className={`rounded-lg px-3 py-2 font-bold ${shootoutTeam==="away"?"bg-[#061a33] text-white ring-2 ring-sky-400":"bg-[#061a33]/70 text-white"}`}>Ciemne</button></div>{automaticShootoutPlayerId?<div className="rounded-lg border bg-white px-3 py-2 font-bold">Automatycznie: #{selectedShootoutPlayers.find(p=>p.id===automaticShootoutPlayerId)?.capNumber} {selectedShootoutPlayers.find(p=>p.id===automaticShootoutPlayerId)?.name}</div>:<select className={input} value={shootoutPlayerId} onChange={e=>setShootoutPlayerId(e.target.value)}><option value="">Wybierz strzelca nr {selectedShootoutEvents.length+1}</option>{selectedShootoutPlayers.filter(p=>p.name).map(p=><option key={p.id} value={p.id}>#{p.capNumber} {p.name}</option>)}</select>}<button onClick={()=>addShootout(true)} className="rounded-lg bg-green-600 px-5 py-2 font-black text-white">G · Gol</button><button onClick={()=>addShootout(false)} className="rounded-lg bg-red-600 px-5 py-2 font-black text-white line-through">G · Pudło</button></div>{shootoutComplete?<div className="mt-3 rounded-lg bg-green-100 p-3 text-center font-black text-green-800">Seria rzutów karnych rozstrzygnięta.</div>:null}</section>:null}
      {editorOpen?<div className="fixed inset-0 z-[140] grid place-items-center bg-slate-950/60 p-3"><section className="w-full max-w-2xl rounded-2xl bg-white p-4 shadow-2xl"><div className="flex justify-between"><div><small className="font-bold uppercase text-sky-600">{team==="home"?match.home:match.away}</small><h3 className="text-xl font-bold">{editingId?"Edytuj wydarzenie":"Dodaj wydarzenie"}</h3></div><button onClick={()=>setEditorOpen(false)} className="rounded-lg border p-2"><X/></button></div>
        <div className="mt-4 grid grid-cols-3 gap-2" onMouseLeave={()=>setEventMenu(null)}><button onMouseEnter={()=>setEventMenu(null)} onClick={()=>selectKind("goal")} className={`rounded-xl border p-3 font-bold ${kind==="goal"?"border-green-500 bg-green-50 text-green-700":""}`}>G · Gol</button>{(["foul","other"] as const).map(group=><div key={group} className="relative"><button onClick={()=>setEventMenu(eventMenu===group?null:group)} className={`w-full rounded-xl border p-3 text-center font-bold ${selectedOption.group===group?"border-sky-500 bg-sky-50 text-sky-700":""}`}>{group==="foul"?"Przewinienie":"Inne"}</button>{eventMenu===group?<div className={`absolute top-full z-10 mt-1 w-72 rounded-xl border bg-white p-2 shadow-xl ${group==="other"?"right-0":"left-0"}`}>{PROTOCOL_EVENT_OPTIONS.filter(o=>o.group===group&&!o.value.startsWith("shootout_")).map(o=><button key={o.value} onClick={()=>selectKind(o.value)} className="block w-full rounded-lg px-3 py-2 text-left hover:bg-slate-100"><b>{o.symbol||"—"}</b> · {o.label}</button>)}</div>:null}</div>)}</div>
        <div className="mt-4 rounded-xl bg-slate-50 p-3 font-semibold">{eventSymbol(kind)?`${eventSymbol(kind)} · `:""}{selectedOption.label}</div><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Czas<input autoFocus inputMode="numeric" className={`${input} mt-1`} placeholder="627 → 06:27" value={clock} onChange={e=>setClock(e.target.value)} onBlur={()=>setClock(normalizeProtocolClock(clock))}/></label>{!["timeout","official_penalty"].includes(kind)?<label className="text-sm font-semibold">Zawodnik<select className={`${input} mt-1`} value={playerId} onChange={e=>setPlayerId(e.target.value)}><option value="">Wybierz numer czepka</option>{players.map(p=>{const out=playerMajorFouls(protocol.events.filter(e=>e.id!==editingId),p.id)>=3;return <option key={p.id} value={p.id} disabled={out}>#{p.capNumber} {p.name}{out?" — 3 przewinienia, nie może grać":""}</option>})}</select></label>:null}</div><div className="mt-4 flex justify-end gap-2"><button onClick={()=>setEditorOpen(false)} className="rounded-lg border px-4 py-2">Anuluj</button><button onClick={saveEvent} className="inline-flex items-center gap-2 rounded-lg bg-sky-500 px-4 py-2 font-bold text-white"><Check className="h-4 w-4"/>{editingId?"Zapisz zmianę":"Dodaj"}</button></div>
      </section></div>:null}
      {thirdFoulPlayer?<div className="fixed inset-0 z-[160] grid place-items-center bg-red-950/80 p-4"><section role="alertdialog" className="w-full max-w-xl rounded-2xl border-4 border-red-600 bg-white p-7 text-center shadow-2xl"><div className="text-sm font-black uppercase tracking-[0.2em] text-red-600">Zawodnik nie może dalej uczestniczyć w meczu</div><h3 className="mt-3 text-4xl font-black text-red-700">3. PRZEWINIENIE GŁÓWNE</h3><p className="mt-4 text-xl font-bold">#{thirdFoulPlayer.capNumber} {thirdFoulPlayer.name}</p><button autoFocus onClick={()=>setThirdFoulPlayer(null)} className="mt-6 rounded-xl bg-red-600 px-8 py-3 text-lg font-black uppercase text-white">Potwierdzam</button></section></div>:null}
      <section className="rounded-2xl border bg-white"><h3 className="border-b p-3 text-lg font-bold">Przebieg gry</h3><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-sm"><thead><tr className="bg-slate-50 text-left">{["Lp.","Kwarta","Czas","Drużyna","Zawodnik","Symbol","Wynik","Akcje"].map(x=><th key={x} className="p-2">{x}</th>)}</tr></thead><tbody>{protocol.events.map((event,index)=>{const roster=event.team==="home"?homePlayers:awayPlayers,player=roster.find(p=>p.id===event.playerId),running=protocolScore(protocol.events.slice(0,index+1)),quarterStart=index===0||protocol.events[index-1].period!==event.period,goalHit=highlightPlayer&&event.kind==="goal"&&event.playerId===highlightPlayer,foulHit=highlightFoulPlayer&&["exclusion","penalty","exclusion_substitution","brutality","double_exclusion"].includes(event.kind)&&event.playerId===highlightFoulPlayer;return <React.Fragment key={event.id}><tr className={`${quarterStart?"border-t-4 border-t-[#061a33]":"border-t"} transition-colors ${goalHit?"bg-amber-200":foulHit?"bg-red-200":""}`}><td className="p-2">{index+1}</td><td className="p-2 font-bold">{event.period}</td><td className="p-2 tabular-nums">{event.period==="PS"?"—":event.clock}</td><td className="p-2">{event.team==="home"?match.home:match.away}</td><td className="p-2">{player?`#${player.capNumber} ${player.name}`:"Oficjel / drużyna"}</td><td title={eventLabel(event.kind)} className={`p-2 font-bold ${event.kind==="shootout_miss"?"text-red-600 line-through":""}`}>{eventSymbol(event.kind)||"W (obie)"}</td><td className="p-2 font-bold">{running.home}:{running.away}</td><td className="p-2">{live?<div className="flex gap-2"><button onClick={()=>openEdit(event)} className="text-sky-600"><Pencil className="h-4 w-4"/></button><button onClick={()=>setProtocol(p=>({...p,events:p.events.filter(e=>e.id!==event.id)}))} className="text-red-600"><Trash2 className="h-4 w-4"/></button></div>:null}</td></tr>{requiresDisciplinaryDecision(event.kind)&&live?<tr className="bg-red-50/50"><td colSpan={8} className="p-3"><div className="grid gap-2 md:grid-cols-[1fr_auto]"><textarea className={input} placeholder="Uwagi sędziego — wymagane przed zamknięciem" value={event.reason||""} onChange={e=>setDecision(event.id,"reason",e.target.value)}/><div className="rounded-lg border bg-white p-2 text-sm"><b>Rażące zachowanie?</b><label className="ml-3"><input type="radio" name={`g-${event.id}`} checked={event.grossUnsporting===true} onChange={()=>setDecision(event.id,"grossUnsporting",true)}/> Tak</label><label className="ml-3"><input type="radio" name={`g-${event.id}`} checked={event.grossUnsporting===false} onChange={()=>setDecision(event.id,"grossUnsporting",false)}/> Nie</label></div></div></td></tr>:null}</React.Fragment>})}{!protocol.events.length?<tr><td colSpan={8} className="p-5 text-center text-slate-500">{setup?"Przebieg gry będzie dostępny po rozpoczęciu meczu.":"Brak zdarzeń."}</td></tr>:null}</tbody></table></div></section>
      <section className="grid gap-3 rounded-2xl border bg-white p-3 md:grid-cols-2"><label className="text-sm font-bold">Pozostałe uwagi sędziowskie<textarea disabled={!live} className={`${input} mt-1 min-h-28`} value={protocol.refereeNotes} onChange={e=>setProtocol(p=>({...p,refereeNotes:e.target.value}))}/></label><div className="space-y-3"><label className="block text-sm font-bold">Godzina zakończenia<input disabled={!live} type="time" className={`${input} mt-1`} value={protocol.finishedAt} onChange={e=>setProtocol(p=>({...p,finishedAt:e.target.value}))}/></label><label><input disabled={!live} type="checkbox" checked={protocol.protest} onChange={e=>setProtocol(p=>({...p,protest:e.target.checked}))}/> Protest</label></div></section>
      <div className="flex flex-wrap justify-end gap-2 pb-3"><button onClick={()=>{saveProtocol(protocol);alert("Wersja robocza zapisana lokalnie.")}} className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-2 font-bold"><Save className="h-4 w-4"/>Zapisz roboczo</button>{live?<button onClick={submitProtocol} disabled={!canSubmit} className="inline-flex items-center gap-2 rounded-xl bg-green-600 px-4 py-2 font-bold text-white disabled:opacity-40"><FileCheck2 className="h-4 w-4"/>Zamknij i przekaż delegatowi</button>:null}{protocol.status==="submitted"&&canApprove?<><button onClick={reopenProtocol} className="rounded-xl border border-amber-400 bg-amber-50 px-4 py-2 font-bold text-amber-800">Edytuj protokół</button><button onClick={approveProtocol} className="rounded-xl bg-green-700 px-4 py-2 font-bold text-white">Zatwierdź ostatecznie</button></>:null}{protocol.status==="approved"&&canApprove?<button onClick={reopenProtocol} className="rounded-xl border border-amber-400 bg-amber-50 px-4 py-2 font-bold text-amber-800">Edytuj zatwierdzony protokół</button>:null}{protocol.status==="approved"?<button onClick={()=>context&&void generateMatchProtocolPdf(match,protocol,homePlayers,awayPlayers)} className="inline-flex items-center gap-2 rounded-xl bg-sky-500 px-4 py-2 font-bold text-white"><FileDown className="h-4 w-4"/>Pobierz PDF</button>:null}</div>
    </main></div></div>;
}
