import React from "react";
import { Check, FileCheck2, FileDown, Pencil, Plus, Save, Trash2, X } from "lucide-react";
import type { Match, Role } from "../../types/wpolo";
import { generateMatchProtocolPdf } from "../../lib/matchProtocolPdf";
import { PROTOCOL_EVENT_OPTIONS, eventSymbol, loadProtocol, loadProtocolContext, normalizeProtocolClock, playerGoals, playerMajorFoulEvents, playerMajorFouls, protocolScore, requiresDisciplinaryDecision, saveProtocol, type MatchProtocolDraft, type ProtocolContext, type ProtocolEvent, type ProtocolEventKind, type ProtocolPlayer, type ProtocolTeam } from "../../lib/matchProtocol";

type User = { name: string; role: Role; club?: string };
const input = "w-full rounded-lg border border-slate-200 bg-white px-2.5 py-2 text-sm outline-none focus:border-sky-400";
const isDelegate = (user: User, match: Match) => String(user.role).split(/[-+,\s]+/).includes("Admin") || match.delegate === user.name;
const periodLabel = (p: 1|2|3|4|"PS") => p === "PS" ? "Rzuty karne" : `${["I","II","III","IV"][p - 1]} kwarta`;

export function MatchProtocolWorkspace({ match, user, onClose }: { match: Match; user: User; onClose: () => void }) {
  const [protocol, setProtocol] = React.useState<MatchProtocolDraft>(() => loadProtocol(match.id));
  const [context, setContext] = React.useState<ProtocolContext | null>(null);
  const [loading, setLoading] = React.useState(true);
  const [editorOpen, setEditorOpen] = React.useState(false);
  const [editingId, setEditingId] = React.useState<string | null>(null);
  const [team, setTeam] = React.useState<ProtocolTeam>("home");
  const [kind, setKind] = React.useState<ProtocolEventKind>("goal");
  const [playerId, setPlayerId] = React.useState("");
  const [clock, setClock] = React.useState("");
  const [highlightPlayer, setHighlightPlayer] = React.useState<string | null>(null);
  const [highlightFoulPlayer, setHighlightFoulPlayer] = React.useState<string | null>(null);
  const [thirdFoulPlayer, setThirdFoulPlayer] = React.useState<ProtocolPlayer | null>(null);

  React.useEffect(() => { let active = true; setLoading(true); loadProtocolContext(match).then(v => active && setContext(v)).finally(() => active && setLoading(false)); return () => { active = false; }; }, [match]);
  React.useEffect(() => { if (protocol.status === "draft") saveProtocol(protocol); }, [protocol]);
  const homePlayers = context?.homePlayers || [], awayPlayers = context?.awayPlayers || [];
  const players = team === "home" ? homePlayers : awayPlayers;
  const score = protocolScore(protocol.events);
  const timeouts = (side: ProtocolTeam) => protocol.events.filter(e => e.team === side && e.kind === "timeout").length;
  const selectedOption = PROTOCOL_EVENT_OPTIONS.find(o => o.value === kind)!;

  const openNew = (side: ProtocolTeam) => { setEditingId(null); setTeam(side); setKind("goal"); setPlayerId(""); setClock(""); setEditorOpen(true); };
  const openEdit = (event: ProtocolEvent) => { setEditingId(event.id); setTeam(event.team); setKind(event.kind); setPlayerId(event.playerId || ""); setClock(event.clock); setEditorOpen(true); };
  const selectKind = (value: ProtocolEventKind) => { setKind(value); if (["timeout", "official_penalty"].includes(value)) setPlayerId(""); };
  const saveEvent = () => {
    const formatted = normalizeProtocolClock(clock);
    if (!formatted) return alert("Wpisz czas zdarzenia.");
    if (!["timeout", "official_penalty"].includes(kind) && !playerId) return alert("Wybierz zawodnika.");
    if (kind === "timeout" && !editingId && timeouts(team) >= 2) return alert("Ta drużyna wykorzystała już dwa time-outy.");
    const previous = editingId ? protocol.events.find(e => e.id === editingId) : undefined;
    const event: ProtocolEvent = { id: editingId || crypto.randomUUID(), period: previous?.period || protocol.currentPeriod, clock: formatted, team, playerId: playerId || null, kind, reason: previous?.reason, grossUnsporting: previous?.grossUnsporting, createdAt: previous?.createdAt || new Date().toISOString() };
    const withoutEdited = protocol.events.filter(e => e.id !== editingId);
    const becomesThirdMajor = playerId && ["exclusion","penalty","exclusion_substitution","brutality","double_exclusion"].includes(kind) && playerMajorFouls(withoutEdited, playerId) === 2;
    setProtocol(p => ({ ...p, events: editingId ? p.events.map(e => e.id === editingId ? event : e) : [...p.events, event] }));
    setEditorOpen(false); setEditingId(null);
    if (becomesThirdMajor) setThirdFoulPlayer(players.find(p => p.id === playerId) || null);
  };
  const endQuarter = () => {
    if (protocol.currentPeriod === "PS") return;
    if (protocol.currentPeriod === 4) { if (confirm("Zakończyć IV kwartę i przejść do rzutów karnych?")) setProtocol(p => ({ ...p, currentPeriod: "PS" })); return; }
    setProtocol(p => ({ ...p, currentPeriod: (Number(p.currentPeriod) + 1) as 2|3|4 }));
  };
  const setDecision = (id: string, field: "reason"|"grossUnsporting", value: string|boolean) => setProtocol(p => ({ ...p, events: p.events.map(e => e.id === id ? { ...e, [field]: value } : e) }));
  const closeProtocol = () => {
    if (!isDelegate(user, match)) return alert("Protokół może zamknąć wyłącznie delegat tego meczu.");
    if (!protocol.finishedAt) return alert("Wpisz godzinę zakończenia spotkania.");
    if (protocol.events.some(e => requiresDisciplinaryDecision(e.kind) && (!e.reason?.trim() || typeof e.grossUnsporting !== "boolean"))) return alert("Uzupełnij uwagi i decyzję o rażącym niesportowym zachowaniu przy wszystkich oznaczonych zdarzeniach.");
    const closed = { ...protocol, status: "closed" as const, closedAt: new Date().toISOString(), closedBy: user.name }; setProtocol(closed); saveProtocol(closed);
  };

  const timeoutBoxes = (side: ProtocolTeam) => <div className="flex items-center gap-2 text-sm"><b>Time-out:</b>{[0,1].map(i => <span key={i} className={`grid h-7 w-7 place-items-center rounded border-2 font-black ${timeouts(side) > i ? "border-red-400 bg-red-50 text-red-600" : "border-slate-300 text-transparent"}`}>×</span>)}</div>;
  const teamCard = (side: ProtocolTeam, title: string, roster: typeof homePlayers) => <section className={`rounded-xl border ${side === "away" ? "border-sky-200 bg-sky-50" : "border-slate-200 bg-white"}`}>
    <div className="border-b p-3"><b>{title}</b><input disabled={protocol.status === "closed"} className={`${input} mt-2`} placeholder="Trener" value={side === "home" ? protocol.homeCoach : protocol.awayCoach} onChange={e => setProtocol(p => ({ ...p, [side === "home" ? "homeCoach" : "awayCoach"]: e.target.value }))}/></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[430px] text-xs"><thead><tr><th className="p-2 text-left">Nr</th><th className="p-2 text-left">Zawodnik</th><th className="p-2">Bramki</th><th className="p-2" colSpan={3}>Przewinienia główne</th></tr></thead><tbody>{Array.from({length:15},(_,i)=>{const player=roster.find(p=>p.slot===i+1), goals=player?playerGoals(protocol.events,player.id):0, foulEvents=player?playerMajorFoulEvents(protocol.events,player.id):[];return <tr key={i} className={`border-t ${foulEvents.length>=3?"bg-red-50":""}`}><td className="p-2 font-bold">{i+1}</td><td className="p-2">{player?.name||"—"}{player?.isCaptain?" (C)":""}{player?.isGoalkeeper?" (GK)":""}{foulEvents.length>=3?<span className="ml-2 font-bold text-red-600">WYKLUCZONY</span>:""}</td><td className="p-2 text-center"><button disabled={!goals} onMouseEnter={()=>player&&setHighlightPlayer(player.id)} onMouseLeave={()=>setHighlightPlayer(null)} className={goals?"rounded bg-amber-100 px-2 py-1 font-bold text-amber-800":""}>{goals||"—"}</button></td>{[0,1,2].map(n=>{const foul=foulEvents[n],danger=foul&&(n===2||["exclusion_substitution","brutality"].includes(foul.kind));return <td key={n} className="w-10 p-2 text-center">{foul?<button onMouseEnter={()=>player&&setHighlightFoulPlayer(player.id)} onMouseLeave={()=>setHighlightFoulPlayer(null)} className={`rounded px-1.5 py-1 font-black ${danger?"bg-red-600 text-white":"bg-slate-200 text-slate-800"}`}>{eventSymbol(foul.kind)||"W"}</button>:""}</td>})}</tr>})}</tbody></table></div>
    <div className="flex flex-wrap items-center justify-between gap-3 border-t p-3">{timeoutBoxes(side)}{protocol.status === "draft" ? <button onClick={()=>openNew(side)} className={`inline-flex items-center gap-2 rounded-lg border-2 px-4 py-2 font-semibold shadow-sm ${side==="home"?"border-slate-400 bg-white text-[#061a33]":"border-[#061a33] bg-[#061a33] text-white"}`}><span className={`rounded px-2 py-0.5 text-xs ${side==="home"?"bg-slate-100":"bg-white/15"}`}>{side==="home"?"JASNE":"CIEMNE"}</span><Plus className="h-4 w-4"/>Dodaj wydarzenie</button>:null}</div>
  </section>;

  return <div className="fixed inset-0 z-[120] overflow-y-auto bg-slate-950/60 p-2 sm:p-5"><div className="mx-auto min-h-full max-w-7xl rounded-2xl bg-slate-50 shadow-2xl">
    <header className="sticky top-0 z-10 flex justify-between gap-3 rounded-t-2xl border-b bg-white p-4"><div><div className="text-xs font-bold uppercase tracking-widest text-amber-600">Prywatny prototyp — tylko localhost</div><h2 className="text-xl font-bold">Protokół: {match.home} — {match.away}</h2><p className="text-sm text-slate-600">{match.date} • {match.location} • Sędziowie: {match.referees.join(", ")||"—"} • Delegat: {match.delegate||"—"}</p></div><button onClick={onClose} className="rounded-lg border p-2"><X/></button></header>
    <main className="space-y-4 p-3 sm:p-5">{loading?<div className="rounded-xl bg-white p-4">Pobieranie składów…</div>:null}
      <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-white p-3"><div><small className="uppercase text-slate-500">Bieżąca część meczu</small><div className="text-xl font-bold">{periodLabel(protocol.currentPeriod)}</div></div><div className="rounded-xl bg-[#061a33] px-4 py-2 text-xl font-bold text-white">{score.home} : {score.away}</div>{protocol.status==="draft"?<button onClick={endQuarter} className="rounded-lg border border-amber-300 bg-amber-50 px-4 py-2 font-semibold text-amber-800">Koniec kwarty</button>:null}</div>
      <div className="grid gap-3 lg:grid-cols-2">{teamCard("home",match.home,homePlayers)}{teamCard("away",match.away,awayPlayers)}</div>
      {editorOpen?<div className="fixed inset-0 z-[140] grid place-items-center bg-slate-950/60 p-3"><section className="w-full max-w-2xl rounded-2xl bg-white p-4 shadow-2xl"><div className="flex justify-between"><div><small className="font-bold uppercase text-sky-600">{team==="home"?match.home:match.away}</small><h3 className="text-xl font-bold">{editingId?"Edytuj wydarzenie":"Dodaj wydarzenie"}</h3></div><button onClick={()=>setEditorOpen(false)} className="rounded-lg border p-2"><X/></button></div>
        <div className="mt-4 grid grid-cols-3 gap-2"><button onClick={()=>selectKind("goal")} className={`rounded-xl border p-3 font-bold ${kind==="goal"?"border-green-500 bg-green-50 text-green-700":""}`}>G · Gol</button>{(["foul","other"] as const).map(group=><details key={group} className="relative"><summary className={`cursor-pointer list-none rounded-xl border p-3 text-center font-bold ${selectedOption.group===group?"border-sky-500 bg-sky-50 text-sky-700":""}`}>{group==="foul"?"Przewinienie":"Inne"}</summary><div className={`absolute top-full z-10 mt-1 w-72 rounded-xl border bg-white p-2 shadow-xl ${group==="other"?"right-0":"left-0"}`}>{PROTOCOL_EVENT_OPTIONS.filter(o=>o.group===group).map(o=><button key={o.value} onClick={()=>selectKind(o.value)} className="block w-full rounded-lg px-3 py-2 text-left hover:bg-slate-100"><b>{o.symbol||"—"}</b> · {o.label}</button>)}</div></details>)}</div>
        <div className="mt-4 rounded-xl bg-slate-50 p-3 font-semibold">{eventSymbol(kind)?`${eventSymbol(kind)} · `:""}{selectedOption.label}</div><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Czas<input autoFocus inputMode="numeric" className={`${input} mt-1`} placeholder="627 → 06:27" value={clock} onChange={e=>setClock(e.target.value)} onBlur={()=>setClock(normalizeProtocolClock(clock))}/></label>{!["timeout","official_penalty"].includes(kind)?<label className="text-sm font-semibold">Zawodnik<select className={`${input} mt-1`} value={playerId} onChange={e=>setPlayerId(e.target.value)}><option value="">Wybierz numer czepka</option>{players.map(p=>{const out=playerMajorFouls(protocol.events.filter(e=>e.id!==editingId),p.id)>=3;return <option key={p.id} value={p.id} disabled={out}>#{p.capNumber} {p.name}{out?" — 3 przewinienia, nie może grać":""}</option>})}</select></label>:null}</div><div className="mt-4 flex justify-end gap-2"><button onClick={()=>setEditorOpen(false)} className="rounded-lg border px-4 py-2">Anuluj</button><button onClick={saveEvent} className="inline-flex items-center gap-2 rounded-lg bg-sky-500 px-4 py-2 font-bold text-white"><Check className="h-4 w-4"/>{editingId?"Zapisz zmianę":"Dodaj"}</button></div>
      </section></div>:null}
      {thirdFoulPlayer?<div className="fixed inset-0 z-[160] grid place-items-center bg-red-950/80 p-4"><section role="alertdialog" className="w-full max-w-xl rounded-2xl border-4 border-red-600 bg-white p-7 text-center shadow-2xl"><div className="text-sm font-black uppercase tracking-[0.2em] text-red-600">Zawodnik nie może dalej uczestniczyć w meczu</div><h3 className="mt-3 text-4xl font-black text-red-700">3. PRZEWINIENIE GŁÓWNE</h3><p className="mt-4 text-xl font-bold">#{thirdFoulPlayer.capNumber} {thirdFoulPlayer.name}</p><button autoFocus onClick={()=>setThirdFoulPlayer(null)} className="mt-6 rounded-xl bg-red-600 px-8 py-3 text-lg font-black uppercase text-white">Potwierdzam</button></section></div>:null}
      <section className="rounded-2xl border bg-white"><h3 className="border-b p-3 text-lg font-bold">Przebieg gry</h3><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-sm"><thead><tr className="bg-slate-50 text-left">{["Lp.","Kwarta","Czas","Drużyna","Zawodnik","Symbol","Wynik","Akcje"].map(x=><th key={x} className="p-2">{x}</th>)}</tr></thead><tbody>{protocol.events.map((event,index)=>{const roster=event.team==="home"?homePlayers:awayPlayers,player=roster.find(p=>p.id===event.playerId),running=protocolScore(protocol.events.slice(0,index+1)),goalHit=highlightPlayer&&event.kind==="goal"&&event.playerId===highlightPlayer,foulHit=highlightFoulPlayer&&["exclusion","penalty","exclusion_substitution","brutality","double_exclusion"].includes(event.kind)&&event.playerId===highlightFoulPlayer;return <React.Fragment key={event.id}><tr className={`border-t transition-colors ${goalHit?"bg-amber-200":foulHit?"bg-red-200":""}`}><td className="p-2">{index+1}</td><td className="p-2">{event.period}</td><td className="p-2 tabular-nums">{event.clock}</td><td className="p-2">{event.team==="home"?match.home:match.away}</td><td className="p-2">{player?`#${player.capNumber} ${player.name}`:"Oficjel / drużyna"}</td><td className="p-2 font-bold">{eventSymbol(event.kind)||"W (obie)"}</td><td className="p-2 font-bold">{running.home}:{running.away}</td><td className="p-2">{protocol.status==="draft"?<div className="flex gap-2"><button onClick={()=>openEdit(event)} className="text-sky-600"><Pencil className="h-4 w-4"/></button><button onClick={()=>setProtocol(p=>({...p,events:p.events.filter(e=>e.id!==event.id)}))} className="text-red-600"><Trash2 className="h-4 w-4"/></button></div>:null}</td></tr>{requiresDisciplinaryDecision(event.kind)&&protocol.status==="draft"?<tr className="bg-red-50/50"><td colSpan={8} className="p-3"><div className="grid gap-2 md:grid-cols-[1fr_auto]"><textarea className={input} placeholder="Uwagi sędziego — wymagane przed zamknięciem" value={event.reason||""} onChange={e=>setDecision(event.id,"reason",e.target.value)}/><div className="rounded-lg border bg-white p-2 text-sm"><b>Rażące zachowanie?</b><label className="ml-3"><input type="radio" name={`g-${event.id}`} checked={event.grossUnsporting===true} onChange={()=>setDecision(event.id,"grossUnsporting",true)}/> Tak</label><label className="ml-3"><input type="radio" name={`g-${event.id}`} checked={event.grossUnsporting===false} onChange={()=>setDecision(event.id,"grossUnsporting",false)}/> Nie</label></div></div></td></tr>:null}</React.Fragment>})}{!protocol.events.length?<tr><td colSpan={8} className="p-5 text-center text-slate-500">Brak zdarzeń.</td></tr>:null}</tbody></table></div></section>
      <section className="grid gap-3 rounded-2xl border bg-white p-3 md:grid-cols-2"><label className="text-sm font-bold">Pozostałe uwagi sędziowskie<textarea disabled={protocol.status==="closed"} className={`${input} mt-1 min-h-28`} value={protocol.refereeNotes} onChange={e=>setProtocol(p=>({...p,refereeNotes:e.target.value}))}/></label><div className="space-y-3"><label className="block text-sm font-bold">Godzina zakończenia<input disabled={protocol.status==="closed"} type="time" className={`${input} mt-1`} value={protocol.finishedAt} onChange={e=>setProtocol(p=>({...p,finishedAt:e.target.value}))}/></label><label><input disabled={protocol.status==="closed"} type="checkbox" checked={protocol.protest} onChange={e=>setProtocol(p=>({...p,protest:e.target.checked}))}/> Protest</label></div></section>
      <div className="flex flex-wrap justify-end gap-2 pb-3"><button onClick={()=>{saveProtocol(protocol);alert("Wersja robocza zapisana lokalnie.")}} className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-2 font-bold"><Save className="h-4 w-4"/>Zapisz roboczo</button>{protocol.status==="draft"?<button onClick={closeProtocol} disabled={!isDelegate(user,match)} className="inline-flex items-center gap-2 rounded-xl bg-green-600 px-4 py-2 font-bold text-white disabled:opacity-40"><FileCheck2 className="h-4 w-4"/>Zamknij protokół</button>:<button onClick={()=>context&&void generateMatchProtocolPdf(match,protocol,homePlayers,awayPlayers)} className="inline-flex items-center gap-2 rounded-xl bg-sky-500 px-4 py-2 font-bold text-white"><FileDown className="h-4 w-4"/>Pobierz PDF</button>}</div>
    </main></div></div>;
}
