import React from "react";
import { Search, SlidersHorizontal, UserRoundCheck } from "lucide-react";
import { getRefereeDashboard, REFEREE_CLASSES, setRefereeClass, setRefereeMultiplier, type RefereeDashboard, type RefereeClass } from "../../lib/refereeRatings";
import type { Match, Role } from "../../types/wpolo";
import { MatchProtocolWorkspace } from "../matches/MatchProtocolWorkspace";

export function AdminRefereesPage({matches,user}:{matches:Match[];user:{name:string;role:Role;club?:string}}){
 const [data,setData]=React.useState<RefereeDashboard|null>(null),[error,setError]=React.useState(""),[query,setQuery]=React.useState(""),[category,setCategory]=React.useState(""),[klass,setKlass]=React.useState(""),[selectedId,setSelectedId]=React.useState(""),[protocolId,setProtocolId]=React.useState<string|null>(null);
 const load=React.useCallback(async()=>{try{setError("");setData(await getRefereeDashboard());}catch(e){setError(e instanceof Error?e.message:String(e));}},[]); React.useEffect(()=>{void load();},[load]);
 const refs=(data?.referees||[]).filter(r=>(!query||r.name.toLocaleLowerCase("pl").includes(query.toLocaleLowerCase("pl")))&&(!klass||r.class===klass)); const selected=data?.referees.find(r=>r.id===selectedId); const selectedMatches=(selected?.matches||[]).filter(m=>!category||m.categoryId===category); const protocolMatch=matches.find(m=>m.id===protocolId);
 const updateMultiplier=async(kind:"category"|"difficulty",key:string,value:string)=>{const number=Number(value);if(!Number.isFinite(number)||number<=0)return;await setRefereeMultiplier(kind,key,number);await load();};
 return <section className="space-y-4"><div className="rounded-2xl border border-sky-100 bg-[linear-gradient(135deg,#f8fcff,#eef8ff)] p-5"><div className="flex items-center gap-3"><UserRoundCheck className="h-7 w-7 text-sky-600"/><div><div className="text-xs font-semibold uppercase tracking-wider text-sky-600">Tylko administrator</div><h2 className="text-2xl font-bold">Sędziowie</h2></div></div></div>{error&&<div className="rounded-xl bg-red-50 p-3 text-red-700">{error}</div>}
 <div className="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-3"><label className="text-xs font-bold uppercase text-slate-500">Nazwisko<div className="relative mt-1"><Search className="absolute left-3 top-2.5 h-4 w-4"/><input value={query} onChange={e=>setQuery(e.target.value)} className="w-full rounded-xl border py-2 pl-9 pr-3 font-normal normal-case"/></div></label><label className="text-xs font-bold uppercase text-slate-500">Kategoria<select value={category} onChange={e=>setCategory(e.target.value)} className="mt-1 w-full rounded-xl border bg-white px-3 py-2 font-normal normal-case"><option value="">Wszystkie</option>{data?.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="text-xs font-bold uppercase text-slate-500">Klasa<select value={klass} onChange={e=>setKlass(e.target.value)} className="mt-1 w-full rounded-xl border bg-white px-3 py-2 font-normal normal-case"><option value="">Wszystkie</option>{REFEREE_CLASSES.map(c=><option key={c}>{c}</option>)}</select></label></div>
 <div className="grid gap-4 lg:grid-cols-[360px_1fr]"><div className="space-y-2">{refs.map(r=>{const scoped=category?r.matches.filter(m=>m.categoryId===category):r.matches;const scored=scoped.filter(m=>m.weightedScore!==null);const average=scored.length?(scored.reduce((sum,m)=>sum+Number(m.weightedScore),0)/scored.length).toFixed(2):"—";return <button key={r.id} onClick={()=>setSelectedId(r.id)} className={`w-full rounded-xl border p-3 text-left ${selectedId===r.id?"border-sky-400 bg-sky-50":"bg-white"}`}><div className="font-bold">{r.name}</div><div className="mt-1 text-xs text-slate-500">{r.class} • mecze: {scoped.length} • ocena: {average}</div></button>})}</div><div className="rounded-2xl border bg-white p-4">{selected?<><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-xl font-bold">{selected.name}</h3><div className="text-sm text-slate-500">Mecze w filtrze: {selectedMatches.length}</div></div><select value={selected.class} onChange={async e=>{await setRefereeClass(selected.id,e.target.value as RefereeClass);await load();}} className="rounded-xl border bg-white px-3 py-2">{REFEREE_CLASSES.map(c=><option key={c}>{c}</option>)}</select></div><div className="mt-4 space-y-2">{selectedMatches.map(m=><button key={m.id} onClick={()=>setProtocolId(m.id)} className="grid w-full gap-1 rounded-xl bg-slate-50 p-3 text-left text-sm sm:grid-cols-[90px_1fr_auto]"><span>{m.date}</span><span className="font-semibold">{m.home} – {m.away}<span className="block text-xs font-normal text-slate-500">{m.categoryName} • {m.difficulty||"brak trudności"}</span></span><span className="font-bold">{m.weightedScore??"—"}</span></button>)}</div></>:<div className="text-slate-500">Wybierz sędziego, aby zobaczyć jego mecze.</div>}</div></div>
 <div className="rounded-2xl border bg-white p-4"><div className="mb-3 flex items-center gap-2 font-bold"><SlidersHorizontal className="h-5 w-5"/>Mnożniki</div><div className="grid gap-4 lg:grid-cols-2"><div><h4 className="mb-2 text-sm font-bold">Kategorie rozgrywek</h4>{data?.categories.map(c=><label key={c.id} className="mb-2 grid grid-cols-[1fr_100px] items-center gap-2 text-sm"><span>{c.name}</span><input type="number" min="0.1" step="0.05" defaultValue={c.multiplier} onBlur={e=>void updateMultiplier("category",c.id,e.target.value)} className="rounded-lg border px-2 py-1.5"/></label>)}</div><div><h4 className="mb-2 text-sm font-bold">Trudność meczu</h4>{data?.difficulties.map(d=><label key={d.name} className="mb-2 grid grid-cols-[1fr_100px] items-center gap-2 text-sm"><span>{d.name}</span><input type="number" min="0.1" step="0.05" defaultValue={d.multiplier} onBlur={e=>void updateMultiplier("difficulty",d.name,e.target.value)} className="rounded-lg border px-2 py-1.5"/></label>)}</div></div></div>
 {protocolMatch&&<MatchProtocolWorkspace match={protocolMatch} user={user} readOnly onClose={()=>setProtocolId(null)}/>}</section>;
}
