import React from "react";
import { FlaskConical, Pencil, Plus, RotateCcw, Trash2 } from "lucide-react";
import type { Match, Role } from "../../types/wpolo";
import { blankProtocol, protocolScore, type MatchProtocolDraft, type ProtocolPlayer } from "../../lib/matchProtocol";
import { MatchProtocolWorkspace } from "../matches/MatchProtocolWorkspace";

type DemoUser = { name: string; role: Role; club?: string };
type DemoStage = { id: string; name: string };
type DemoTournament = { id: string; stageId: string; name: string };
type DemoData = { version: 1; stages: DemoStage[]; tournaments: DemoTournament[]; matches: Match[]; protocols: Record<string, MatchProtocolDraft> };

const SERBIA = ["Radoslav Filipovic","Strahinja Rasovic","Milos Cuk","Sava Randelovic","Nikola Jaksic","Dusan Mandic","Viktor Rasovic","Nemanja Vico","Nikola Dedovic","Nemanja Ubovic","Radomir Drasovic","Petar Jaksic","Vladimir Misovic"];
const CROATIA = ["Marko Bijac","Rino Buric","Loren Fatovic","Luka Loncar","Maro Jokovic","Konstantin Kharkov","Ante Vukicevic","Marko Zuvela","Jerko Marinic Kragic","Josip Vrlic","Luka Bukic","Matias Biljaka","Toni Popadic"];
const players = (side: "srb"|"cro", names: string[]): ProtocolPlayer[] => names.map((name, index) => ({ id: `demo-${side}-${index + 1}`, slot: index + 1, capNumber: index + 1, name, isGoalkeeper: index === 0 || index === 12, isCaptain: index === (side === "srb" ? 4 : 0) }));
const emptyMatch = (overrides: Partial<Match>): Match => ({ id: crypto.randomUUID(), date: new Date().toISOString().slice(0,10), location: "", home: "", away: "", referees: [], commsByClub: {}, rosterByClub: {}, matchReport: null, reportPhotos: [], uploadsLog: [], ...overrides });

function seedData(): DemoData {
  const match = emptyMatch({ id: "demo-paris-2024-final", date: "2024-08-11", time: "14:00", round: "Finał", location: "Paris La Défense Arena", home: "Serbia", away: "Chorwacja", result: "", referees: [], delegate: "", stageId: "demo-stage-paris", tournamentId: "demo-tournament-paris" });
  const protocol: MatchProtocolDraft = { ...blankProtocol(match.id), homePlayers: players("srb", SERBIA), awayPlayers: players("cro", CROATIA), homeCoach: "Uros Stevanovic", awayCoach: "Ivica Tucak", updatedAt: new Date().toISOString() };
  return { version: 1, stages: [{ id: "demo-stage-paris", name: "Igrzyska Olimpijskie Paryż 2024" }], tournaments: [{ id: "demo-tournament-paris", stageId: "demo-stage-paris", name: "Turniej olimpijski mężczyzn" }], matches: [match], protocols: { [match.id]: protocol } };
}

const input = "rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm outline-none focus:border-sky-400";
const button = "inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-semibold text-[#061a33] hover:bg-sky-50";

export function DemoPage({ user }: { user: DemoUser }) {
  const storageKey = React.useMemo(() => `wpolo:demo:v1:${user.name}`, [user.name]);
  const [data, setData] = React.useState<DemoData>(() => { try { const raw = localStorage.getItem(storageKey); return raw ? JSON.parse(raw) : seedData(); } catch { return seedData(); } });
  const [protocolMatchId, setProtocolMatchId] = React.useState<string | null>(null);
  const [stageName, setStageName] = React.useState("");
  const [tournamentName, setTournamentName] = React.useState("");
  const [tournamentStageId, setTournamentStageId] = React.useState("");
  const [matchForm, setMatchForm] = React.useState({ home: "", away: "", date: "", time: "", location: "", round: "", stageId: "", tournamentId: "" });
  React.useEffect(() => { localStorage.setItem(storageKey, JSON.stringify(data)); }, [data, storageKey]);
  React.useEffect(() => { setTournamentStageId(data.stages[0]?.id || ""); setMatchForm(form => ({ ...form, stageId: data.stages[0]?.id || "", tournamentId: data.tournaments[0]?.id || "" })); }, []);

  const updateProtocol = React.useCallback((protocol: MatchProtocolDraft) => setData(current => ({ ...current, protocols: { ...current.protocols, [protocol.matchId]: protocol } })), []);
  const addStage = () => { if (!stageName.trim()) return; setData(d => ({ ...d, stages: [...d.stages, { id: crypto.randomUUID(), name: stageName.trim() }] })); setStageName(""); };
  const addTournament = () => { if (!tournamentName.trim() || !tournamentStageId) return; setData(d => ({ ...d, tournaments: [...d.tournaments, { id: crypto.randomUUID(), stageId: tournamentStageId, name: tournamentName.trim() }] })); setTournamentName(""); };
  const addMatch = () => {
    if (!matchForm.home.trim() || !matchForm.away.trim() || !matchForm.date) return alert("Wpisz obie drużyny i datę meczu.");
    const match = emptyMatch({ ...matchForm, home: matchForm.home.trim(), away: matchForm.away.trim(), stageId: matchForm.stageId || null, tournamentId: matchForm.tournamentId || null });
    setData(d => ({ ...d, matches: [...d.matches, match], protocols: { ...d.protocols, [match.id]: blankProtocol(match.id) } }));
    setMatchForm(form => ({ ...form, home: "", away: "", date: "", time: "", location: "", round: "" }));
  };
  const editName = (kind: "stage"|"tournament", id: string, oldName: string) => { const name = prompt("Nowa nazwa", oldName)?.trim(); if (!name) return; setData(d => ({ ...d, [kind === "stage" ? "stages" : "tournaments"]: d[kind === "stage" ? "stages" : "tournaments"].map((item: DemoStage|DemoTournament) => item.id === id ? { ...item, name } : item) } as DemoData)); };
  const editMatch = (match: Match) => { const home = prompt("Gospodarz", match.home)?.trim(), away = prompt("Gość", match.away)?.trim(); if (!home || !away) return; const location = prompt("Miejsce", match.location) ?? match.location; setData(d => ({ ...d, matches: d.matches.map(item => item.id === match.id ? { ...item, home, away, location } : item) })); };
  const removeMatch = (id: string) => { if (!confirm("Usunąć ten mecz z lokalnego DEMO?")) return; setData(d => { const protocols = { ...d.protocols }; delete protocols[id]; return { ...d, matches: d.matches.filter(m => m.id !== id), protocols }; }); };
  const approve = (match: Match) => { const protocol = data.protocols[match.id]; if (!protocol || protocol.status !== "submitted") return; const score = protocolScore(protocol.events); const approved = { ...protocol, status: "approved" as const, approvedAt: new Date().toISOString(), approvedBy: user.name, updatedAt: new Date().toISOString() }; setData(d => ({ ...d, matches: d.matches.map(m => m.id === match.id ? { ...m, result: `${score.home}:${score.away}`, shootout: protocol.events.some(e => e.period === "PS") } : m), protocols: { ...d.protocols, [match.id]: approved } })); };
  const reset = () => { if (!confirm("Przywrócić początkowe dane DEMO? Wszystkie lokalne zmiany zostaną usunięte.")) return; const seeded = seedData(); localStorage.setItem(storageKey, JSON.stringify(seeded)); setData(seeded); setProtocolMatchId(null); };
  const openMatch = protocolMatchId ? data.matches.find(m => m.id === protocolMatchId) : null;

  return <section className="space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4"><div><div className="flex items-center gap-2 text-xl font-bold text-[#061a33]"><FlaskConical className="h-5 w-5 text-amber-600"/>DEMO</div><p className="mt-1 max-w-3xl text-sm text-slate-700">Plac zabaw zapisuje dane wyłącznie w tej przeglądarce. Nic z tej strony nie trafia do głównych rozgrywek ani do serwera i nie wpływa na innych użytkowników.</p></div><button className={button} onClick={reset}><RotateCcw className="h-4 w-4"/>Reset do przykładu</button></div>

    <div className="grid gap-4 lg:grid-cols-2">
      <div className="rounded-2xl border border-sky-100 bg-[#f8fcff] p-4"><h3 className="font-bold">Etapy</h3><div className="mt-3 flex gap-2"><input className={`${input} min-w-0 flex-1`} value={stageName} onChange={e=>setStageName(e.target.value)} placeholder="Nazwa etapu"/><button className={button} onClick={addStage}><Plus className="h-4 w-4"/>Dodaj</button></div><div className="mt-3 space-y-2">{data.stages.map(stage=><div key={stage.id} className="flex items-center justify-between rounded-xl border bg-white p-3 text-sm"><span>{stage.name}</span><div className="flex gap-1"><button title="Edytuj" onClick={()=>editName("stage",stage.id,stage.name)} className="p-1.5"><Pencil className="h-4 w-4"/></button><button title="Usuń" onClick={()=>setData(d=>({...d,stages:d.stages.filter(s=>s.id!==stage.id)}))} className="p-1.5 text-red-500"><Trash2 className="h-4 w-4"/></button></div></div>)}</div></div>
      <div className="rounded-2xl border border-sky-100 bg-[#f8fcff] p-4"><h3 className="font-bold">Turnieje</h3><div className="mt-3 grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><input className={input} value={tournamentName} onChange={e=>setTournamentName(e.target.value)} placeholder="Nazwa turnieju"/><select className={input} value={tournamentStageId} onChange={e=>setTournamentStageId(e.target.value)}>{data.stages.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button className={button} onClick={addTournament}><Plus className="h-4 w-4"/>Dodaj</button></div><div className="mt-3 space-y-2">{data.tournaments.map(t=><div key={t.id} className="flex items-center justify-between rounded-xl border bg-white p-3 text-sm"><span><b>{t.name}</b><small className="ml-2 text-slate-500">{data.stages.find(s=>s.id===t.stageId)?.name}</small></span><div className="flex gap-1"><button title="Edytuj" onClick={()=>editName("tournament",t.id,t.name)} className="p-1.5"><Pencil className="h-4 w-4"/></button><button title="Usuń" onClick={()=>setData(d=>({...d,tournaments:d.tournaments.filter(x=>x.id!==t.id)}))} className="p-1.5 text-red-500"><Trash2 className="h-4 w-4"/></button></div></div>)}</div></div>
    </div>

    <div className="rounded-2xl border border-sky-100 bg-white p-4"><h3 className="font-bold">Dodaj mecz</h3><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><input className={input} placeholder="Gospodarz" value={matchForm.home} onChange={e=>setMatchForm({...matchForm,home:e.target.value})}/><input className={input} placeholder="Gość" value={matchForm.away} onChange={e=>setMatchForm({...matchForm,away:e.target.value})}/><input className={input} type="date" value={matchForm.date} onChange={e=>setMatchForm({...matchForm,date:e.target.value})}/><input className={input} type="time" value={matchForm.time} onChange={e=>setMatchForm({...matchForm,time:e.target.value})}/><input className={input} placeholder="Miejsce" value={matchForm.location} onChange={e=>setMatchForm({...matchForm,location:e.target.value})}/><input className={input} placeholder="Runda / kolejka" value={matchForm.round} onChange={e=>setMatchForm({...matchForm,round:e.target.value})}/><select className={input} value={matchForm.stageId} onChange={e=>setMatchForm({...matchForm,stageId:e.target.value})}><option value="">Bez etapu</option>{data.stages.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select className={input} value={matchForm.tournamentId} onChange={e=>setMatchForm({...matchForm,tournamentId:e.target.value})}><option value="">Bez turnieju</option>{data.tournaments.filter(t=>!matchForm.stageId||t.stageId===matchForm.stageId).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div><button className={`${button} mt-3 bg-sky-500 text-white hover:bg-sky-600`} onClick={addMatch}><Plus className="h-4 w-4"/>Dodaj mecz</button></div>

    <div className="rounded-2xl border border-sky-100 bg-white p-4"><h3 className="font-bold">Mecze DEMO</h3><div className="mt-3 space-y-3">{data.matches.map(match=>{const protocol=data.protocols[match.id]||blankProtocol(match.id);return <article key={match.id} className="rounded-2xl border border-sky-100 bg-[#f8fcff] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-xs uppercase tracking-wide text-slate-500">{match.round||"Mecz"} • {match.date}{match.time?` • ${match.time}`:""}</div><div className="mt-1 font-bold">{match.home} — {match.away}</div><div className="text-sm text-slate-600">{match.location||"Miejsce nieustalone"}{match.result?` • Wynik ${match.result}`:""}</div><div className="mt-1 text-xs font-semibold text-amber-700">Status protokołu: {protocol.status}</div></div><div className="flex flex-wrap gap-2"><button className={button} onClick={()=>editMatch(match)}><Pencil className="h-4 w-4"/>Edytuj</button><button className={button} onClick={()=>setProtocolMatchId(match.id)}>Protokół</button>{protocol.status==="submitted"?<button className={`${button} border-green-300 bg-green-50 text-green-700`} onClick={()=>approve(match)}>Zatwierdź protokół</button>:null}<button className={`${button} text-red-600`} onClick={()=>removeMatch(match.id)}><Trash2 className="h-4 w-4"/>Usuń</button></div></div></article>})}</div></div>
    {openMatch ? <MatchProtocolWorkspace match={openMatch} user={user} localOnly initialProtocol={data.protocols[openMatch.id] || blankProtocol(openMatch.id)} onLocalProtocolChange={updateProtocol} onProtocolChanged={async status=>{ if(status==="setup"||status==="live") setData(d=>({...d,matches:d.matches.map(m=>m.id===openMatch.id?{...m,result:"",shootout:false}:m)})); }} onClose={()=>setProtocolMatchId(null)}/> : null}
  </section>;
}
