import type { Player } from "../../types/club";

export const mockPlayers: Player[] = [
  {
    id: "p1",
    firstName: "Jan",
    lastName: "Kowalski",
    gender: "M",
    birthYear: 2002,
    capNumber: 1,
    licenseNumber: "LIC-001",
    licenseVerified: true,
    licenseVerifiedAt: "2026-06-01T10:00:00Z",
    licenseVerifiedBy: "Delegat Demo",
    licenseValidUntil: "2026-12-31T00:00:00Z",
  },
  {
    id: "p2",
    firstName: "Marek",
    lastName: "Nowak",
    gender: "M",
    birthYear: 2004,
    capNumber: 7,
    licenseNumber: "LIC-002",
    loanFromClub: "KS Poznan",
    loanClub: "AZS UW Warszawa",
    licenseVerified: false,
    licenseValidUntil: "2026-07-10T00:00:00Z",
  },
  {
    id: "p3",
    firstName: "Piotr",
    lastName: "Zielinski",
    gender: "M",
    birthYear: 2001,
    capNumber: 10,
    licenseNumber: "LIC-003",
    licenseVerified: true,
    licenseVerifiedAt: "2026-06-03T09:30:00Z",
    licenseVerifiedBy: "Sedzia Demo",
    licenseValidUntil: "2026-07-15T00:00:00Z",
  },
  {
    id: "p4",
    firstName: "Adam",
    lastName: "Lewandowski",
    gender: "M",
    birthYear: 2005,
    capNumber: 12,
    licenseNumber: "LIC-004",
    licenseVerified: true,
    licenseVerifiedAt: "2026-05-22T11:00:00Z",
    licenseVerifiedBy: "Sedzia Glowny",
    licenseValidUntil: "2026-08-05T00:00:00Z",
  },
  {
    id: "p5",
    firstName: "Pawel",
    lastName: "Wisniewski",
    gender: "M",
    birthYear: 2003,
    capNumber: 5,
    licenseNumber: "LIC-005",
    licenseVerified: false,
  },
  {
    id: "p6",
    firstName: "Kamil",
    lastName: "Wojcik",
    gender: "M",
    birthYear: 2006,
    capNumber: 14,
    licenseNumber: "LIC-006",
    licenseVerified: true,
    licenseVerifiedAt: "2026-06-07T08:15:00Z",
    licenseVerifiedBy: "Delegat Turnieju",
    licenseValidUntil: "2026-09-01T00:00:00Z",
  },
];